- name: Второй кластер
  hosts: replica
  become: yes

  tasks:

    - name: Каталог
      file:
        path: /pg_data/16-one-base
        state: directory
        owner: postgres
        mode: '0700'

    - name: initdb
      shell: sudo -u postgres /usr/lib/postgresql/17/bin/initdb -D /pg_data/16-one-base